### PR TITLE
Added sub module with ReadyApi4J Groovy DSL samples

### PR DESCRIPTION
**Pull request by prakashmrec**
I think we should rename this repo to 'readyapi4j-samples'. But that's for another PR.

### CODE REVIEW

**Comment by olensmar** [comment]
I kindof agree with @spindelmanne - perhaps its better to have a samples submodule in readyapi4j with all samples in there?

**Comment by prakashmrec** [comment]
That would be even better, everything in one place. Only concern I have is that we should not build the samples (run sample tests) as part of regular readyapi4j build. Since it has dependency on our public TestServer and the tests there might fail from time to time. @olensmar, @spindelmanne ?

**Comment by olensmar** [comment]
agreed - perhaps we can disable those tests by default and have a property to enable them? (or the other way around)

**Comment by olensmar** [comment]
also - i can add a cucumber sample to the readyapi4j repo...

**Comment by prakashmrec** [comment]
sounds good, please merge this PR (unless you have some feedback on the changes) and I will port these samples to readyapi4j in a submodule.

**Comment by olensmar** [comment]
ok - but I suggest we aim to move all samples to readyapi4j and to remove this repo altogether

**Pull request merged**
